services:
  surrealdb:
    container_name: surrealdb_test
    restart: unless-stopped
    entrypoint:
      - /surreal
      - start
      - --allow-guests
      - --bind
      - 0.0.0.0:8000
      - --user
      - root
      - --pass
      - root
      - memory
      
    image: surrealdb/surrealdb:v2.0.0-alpha.4
    ports:
      - 8000:8000